import Image from "next/image";
import Link from "next/link";
export default function MedicalMarijuana() {
    return (
        <>
            <section className="service-media-section patient-listing">
                <div className="container">
                    <h2><span class="light-green-txt">Medical Marijuana</span> Doctors & Services & Assessments</h2>
                    <div className="row">
                        <div className="col-md-5">
                            <div className="image-medical-code">
                                <Image src="/images/servicepage/medical-link.png" width={490} height={285} alt="check" />
                            </div>
                        </div>
                        <div className="col-md-7">
                            <div className="design-servicee-uty">
                                <h3><span class="light-green-txt">Medical Marijuana</span> - How to Get MMJ Card</h3>
                                <span className="certification">Our Certification Process is Simple & Painless!</span>
                                <ul>
                                    <li>
                                        <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                                        Schedule your certification appointment.
                                    </li>
                                    <li>
                                        <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                                        Complete Our Intake Form
                                    </li>
                                    <li>
                                        <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                                        Obtain your Medical Marijuana Dispensary Card
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <ul className="secound-service-listing">
                        <li>
                            <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                            Pennsylvania residents are required to pay the state fee through the online profile set up with the PA Dept. of Health&#39;s MMP. The medical marijuana ID card will arrive in the mail within a few short days. Once your medical marijuana card arrives you will be legally permitted to purchase your medical marijuana prescription at your local dispensary.
                        </li>
                        <li>
                            <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                            Ohio residents are required to pay the state fee via an email generated by the OH MMCP. The card can be downloaded, showing evidence of the QR code or printed. Once the card is active you are able to visit your local dispensary on the same day as the certification!
                        </li>
                        <li>
                            <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                            West Virginia residents will need to create an account through the OMC. Your certification will be electronically submitted through your state portal. Once you complete your state registration, payment for your card may be submitted. A check or money order can be sent to
                        </li>
                        <li>
                            <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                            350 capitol Street- room 523-Charleston WV,25301
                        </li>
                        <li>
                            <Image src="/images/homepage/check-light.svg" width={20} height={20} alt="check" />
                            Once the card is active you will be legally permitted to purchase your medical marijuana prescription at your local dispensary.
                        </li>
                    </ul>
                    <div className="butt-doctor-service">
                        <Link href="/schedule" className="green-btn site-btn">Schedule Now</Link>
                        <Link href="/am-i-eligible" className="yellow-btn site-btn">Do I Qualify?</Link>
                    </div>
                </div>
            </section>
        </>
    )
}